import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import { Theme } from "./lib/types/enums";

/** Fonts to be chosen later */

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookieStore = await cookies();
	let theme: Theme = Theme.Light;

	if (cookieStore.has("theme")) {
		theme = cookieStore.get("theme")?.value as Theme;
	}

	return (
		<html
			lang="en"
			className="scroll-smooth "
			data-theme={`${theme === Theme.Light ? "" : "dark"}`}>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				{children}
			</body>
		</html>
	);
}
